version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  auth-service:
    container_name: as_auth-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "node /opt/auth-service/scripts/wait4.js auth-service && npm run start"
    networks:
      - mojaloop-net
    ports:
      - "4004:4004"
    depends_on:
      - mysql
    volumes:
      - ./scripts/wait4.js:/opt/auth-service/scripts/wait4.js
      - ./scripts/wait4.config.js:/opt/auth-service/scripts/wait4.config.js
      - ./config/integration_db.json:/opt/auth-service/config/default_db.json
    healthcheck:
      test: wget -q http://172.17.0.1:4004/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
  
  mysql:
    image: mysql/mysql-server
    container_name: as_mysql
    ports:
      - "3306:3306"
    networks:
      - mojaloop-net
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-auth-service}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-auth-service}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s